default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost

development:
  <<: *default
  database: simpliconsig_development
  username: dhionuxconsignado
  password: DhioRails1123581321345589

test:
  <<: *default
  database: simpliconsig_test
  username: dhionuxconsignado
  password: DhioRails1123581321345589

production:
  <<: *default
  database: simpliconsig_production
  username: dhionuxconsignado
  password: <%= ENV["SIMPLICONSIG_DATABASE_PASSWORD"] %>
